### ISSUE TITLE
GitHub keys should be removed from the public repository

### ISSUE THREAD

**Issue by DanielKehoe** [mokus80/learners_directory#10]
The file _config/initializers/omniauth.rb_ contains your GitHub access keys and is available in the public repo. That means someone can use your keys for their own purposes.

You can use environment variables instead. See my article:
http://railsapps.github.io/rails-environment-variables.html
or the "Configure" chapter of the "Learning Rails" book
or an example application:
https://github.com/RailsApps/rails3-mongoid-omniauth

**Comment by PragTob** [comment]
:+1:

**Comment by netroy** [comment]
keys still exist in https://github.com/mokus80/learners_directory/blob/master/.env
- remove that file with `git rm .env`
- add it to `gitignore`
- update the readme to include info about the `.env` file & everyone who checks out the code, needs to create it.

**Comment by mokus80** [comment]
These are the old keys, I generated new ones. However, you are right, I should remove this file.
