### ISSUE TITLE
Github icon does not appear on log-in button in production mode

### ISSUE THREAD

**Issue by mokus80** [mokus80/learners_directory#7]
It works in development mode, but not in production mode.

**Comment by PragTob** [comment]
Also not when you start the application in production mode locally or just really at heroku?

**Comment by mokus80** [comment]
It doesn't appear on either.

**Comment by PragTob** [comment]
Then it's easier to fix :-) Probably some compilation issue with the assets. `rake assets:precompile` could solve it
